version: '2'

services:
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_conf_8a:/opt/sonarqube/conf
      - sonarqube_data_8a:/opt/sonarqube/data
      - sonarqube_extensions_8a:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins_8a:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql_8a:/var/lib/postgresql
      - postgresql_data_8a:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_conf_8a:
  sonarqube_data_8a:
  sonarqube_extensions_8a:
  sonarqube_bundled-plugins_8a:
  postgresql_8a:
  postgresql_data_8a: