package mx.edu.utez.server.kernel;

public enum Errors {
    INVALID_FIELDS,
    MISSING_FIELDS,
    DATA_TYPE_WRONG,
    REVIEW_REQUEST,
    NO_DATA_FOUND,
    RECORDS_ARE_NOT_RELATED,
    RECORD_NOT_REGISTERED,
    RECORD_NOT_UPDATED,
    RECORD_NOT_DELETED,
    RECORD_HAS_DEPENDENCIES,

    // Area
    DUPLICATED_AREA,
    NO_AREA_FOUND,
    AREA_HAS_DEPENDENCIES,
    AREA_IS_INACTIVE,

    // Specitality
    DUPLICATED_SPECIALITY,
    NO_SPECIALITY_FOUND,
    SPECIALITY_HAS_DEPENDENCIES,
    SPECIALITY_IS_INACTIVE,
    // Status
    NO_STATUS_FOUND,
    DUPLICATED_USER,

    // Session
    CREDENTIALS_MISMATCH,
    USER_IS_INACTIVE,
    USER_IS_BLOCKED,
    SERVER_ERROR,
}
